version: 2
jobs:
  build:
    working_directory: ~/Core2D
    docker:
      - image: microsoft/dotnet:sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore src/Core2D.Editor
      - run: dotnet build src/Core2D.Editor/Core2D.Editor.csproj -c Release -f netstandard2.0
      - run: dotnet restore tests/Core2D.UnitTests
      - run: dotnet test tests/Core2D.UnitTests/Core2D.UnitTests.csproj -c Release -f netcoreapp2.0
      - run: dotnet restore apps/Core2D.Avalonia
      - run: dotnet build apps/Core2D.Avalonia/Core2D.Avalonia.csproj -c Release -f netcoreapp2.0
    notify:
      webhooks:
        - url: https://webhooks.gitter.im/e/18bc2743c91ff21c0246
